---
- name: Install dovecot
  yum: name={{ item }} state=present
  with_items:
    - dovecot.x86_64
    - dovecot-pgsql.x86_64

- name: Copy dovecot configuration
  template: src={{ item }} dest=/etc/dovecot/{{ item }}
  with_items:
    - dovecot.conf
    - dovecot-sql.conf.ext
  notify: restart dovecot

- name: Copy dovecot conf.d
  template: src={{ item }} dest=/etc/dovecot/conf.d/{{ item }}
  with_items:
    - 10-auth.conf
    - 10-master.conf
    - 10-mail.conf
  notify: restart dovecot

- name: Dovecot service state
  service: name=dovecot state=started enabled=yes

