---
- name: Install postfix
  yum: name=postfix state=present

- name: Copy postfix configuration
  template: src=main.cf dest=/etc/postfix/main.cf
  notify: restart postfix
  
- name: Create postfix psql conf dir
  file: path=/etc/postfix/pgsql state=directory
  
- name: Copy postfix postgres conf
  template: src={{ item }} dest=/etc/postfix/pgsql/{{ item }}
  with_items:
    - aliases.cf
    - domains.cf
    - mailboxes.cf
  notify: restart postfix

- name: Add mail group
  group: name=mail gid=200
  
- name: Add mailreader user
  user: name=mailreader group=mail uid=200 home=/home/mail shell=/sbin/nologin

- name: Postfix service state
  service: name=postfix state=started enabled=yes