---
- name: Install postgres
  yum: name={{ item }} state=present
  with_items:
    - postgresql-server
    - postgresql-contrib
    - python-psycopg2

- name: Initiate database
  command: service postgresql initdb
           creates=/var/lib/pgsql/data/postgresql.conf

- name: Copy postgres hba configuration
  template: src=pg_hba.conf dest=/var/lib/pgsql/data/pg_hba.conf
            owner=postgres group=postgres mode='0600'
  notify: restart postgres

- name: Postgresql service state
  service: name=postgresql state=started enabled=yes

- name: Ensure database is created
  become: true
  become_user: postgres
  postgresql_db: name={{ db_name }}
                 encoding='UTF-8'
                 lc_collate='en_US.UTF-8'
                 lc_ctype='en_US.UTF-8'
                 template='template0'
                 state=present

- name: Ensure user has access to the database
  become: true
  become_user: postgres
  postgresql_user: db={{ db_name }}
                   name={{ db_user }}
                   password={{ db_password }}
                   priv=ALL
                   state=present

- name: Ensure user does not have unnecessary privileges
  become: true
  become_user: postgres
  postgresql_user: name={{ db_user }}
                   role_attr_flags=NOSUPERUSER,NOCREATEDB
                   state=present
